name: Auto Login Bot

on:
  schedule:
    - cron: '0 2 * * 1-5' # At 7 am on Mon-Fri
  push:
    branches:    
      - main
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Dummy input
        options: 
        - foo
        - bar

jobs:
  do-auto-login:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      
      - name: Set Timezone
        run: |
         sudo timedatectl set-timezone Asia/Kolkata
         timedatectl
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.4' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install pyotp
          pip install webdriver_manager
#          pip install -r requirements.txt
          
      - name: execute python login script # run main.py
        env:
          USERNAMES: ${{ secrets.USERNAMES }}
          PASSWORDS: ${{ secrets.PASSWORDS }}
          TOTP: ${{ secrets.TOTP }}
        run: python auto_login.py
